services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Next.js Dockerfile
    ports:
      - '3000:3000' # Expose Next.js port
    networks:
      - app-network
    env_file:
      - .env # Load environment variables from .env file

networks:
  app-network:
    driver: bridge
